export const AUTHLOGIN_REQUEST = "AUTHLOGIN_REQUEST";
export const AUTHLOGIN_SUCCESS = "AUTHLOGIN_SUCCESS";
export const AUTHLOGIN_FAIL = "AUTHLOGIN_FAIL";
export const AUTHLOGIN_RESET = "AUTHLOGIN_RESET";
